# Generated by Django 5.2.4 on 2025-08-05 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_telefono"),
        ("instructores", "0002_alter_instructor_telefono"),
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aprendiz",
            options={
                "ordering": ["apellido", "nombre"],
                "verbose_name": "Aprendiz",
                "verbose_name_plural": "Aprendices",
            },
        ),
        migrations.RemoveField(
            model_name="aprendiz",
            name="programa",
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="ciudad",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="fecha_nacimiento",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="telefono",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name="AprendizCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Inscripción"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INS", "Inscrito"),
                            ("ACT", "Activo"),
                            ("DES", "Desertor"),
                            ("GRA", "Graduado"),
                            ("SUS", "Suspendido"),
                        ],
                        default="INS",
                        max_length=3,
                        verbose_name="Estado en el Curso",
                    ),
                ),
                (
                    "nota_final",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Nota Final",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "aprendiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aprendices.aprendiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprendiz por Curso",
                "verbose_name_plural": "Aprendices por Curso",
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Código del curso"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Curso"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Finalización")),
                ("horario", models.CharField(max_length=100, verbose_name="Horario")),
                ("aula", models.CharField(max_length=50, verbose_name="Aula/Ambiente")),
                (
                    "cupos_maximos",
                    models.PositiveIntegerField(verbose_name="Cupos Máximos"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PRO", "Programado"),
                            ("INI", "Iniciado"),
                            ("EJE", "En Ejecución"),
                            ("FIN", "Finalizado"),
                            ("CAN", "Cancelado"),
                            ("SUS", "Suspendido"),
                        ],
                        default="PRO",
                        max_length=3,
                        verbose_name="Estado del Curso",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "aprendices",
                    models.ManyToManyField(
                        related_name="cursos",
                        through="aprendices.AprendizCurso",
                        to="aprendices.aprendiz",
                        verbose_name="Aprendices",
                    ),
                ),
                (
                    "instructor_coordinador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos_coordinados",
                        to="instructores.instructor",
                        verbose_name="Instructor Coordinador",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programas.programa",
                        verbose_name="Programa de Formación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.AddField(
            model_name="aprendizcurso",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aprendices.curso"
            ),
        ),
        migrations.CreateModel(
            name="InstructorCurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(max_length=100, verbose_name="Rol del Curso")),
                (
                    "fecha_asignacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aprendices.curso",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instructores.instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instructor por Curso",
                "verbose_name_plural": "Instructores por Curso",
                "unique_together": {("instructor", "curso")},
            },
        ),
        migrations.AddField(
            model_name="curso",
            name="instructores",
            field=models.ManyToManyField(
                related_name="cursos_impartidos",
                through="aprendices.InstructorCurso",
                to="instructores.instructor",
                verbose_name="Instructores",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aprendizcurso",
            unique_together={("aprendiz", "curso")},
        ),
    ]
