# Generated by Django 5.2.4 on 2025-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_options_remove_aprendiz_programa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aprendiz",
            name="programa",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
