# Generated by Django 5.2.4 on 2025-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0002_alter_aprendiz_telefono"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="aprendiz",
            options={
                "ordering": ["apellido", "nombre"],
                "verbose_name": "Aprendiz",
                "verbose_name_plural": "Aprendices",
            },
        ),
        migrations.RemoveField(
            model_name="aprendiz",
            name="programa",
        ),
        migrations.AlterField(
            model_name="aprendiz",
            name="fecha_nacimiento",
            field=models.DateField(null=True),
        ),
    ]
