# Generated by Django 5.2.4 on 2025-08-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aprendices", "0003_aprendiz_programa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aprendiz",
            name="programa",
        ),
    ]
