# Generated by Django 5.2.4 on 2025-07-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadania'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=10, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField(null=True)),
                ('nivel_educativo', models.CharField(choices=[('TEC', 'Técnico'), ('TGL', 'Técnologo'), ('PRE', 'Pregrado'), ('ESP', 'Epecializacón'), ('MAE', 'Maestría'), ('DOC', 'Doctorado')], default='MAE', max_length=3)),
                ('especialidad', models.CharField(max_length=100)),
                ('anos_experiencia', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateField()),
                ('fecha_registro', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
