# Generated by Django 5.2.4 on 2025-08-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="telefono",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
