# Generated by Django 5.1.6 on 2025-08-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0002_alter_instructor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
